var pokemon_info = {
'sprigatito': ['grass'], 
'floragato': ['grass'], 
'meowscarada': ['grass', 'dark'], 
'fuecoco': ['fire'], 
'crocalor': ['fire'], 
'skeledirge': ['fire', 'ghost'], 
'quaxly': ['water'], 
'quaxwell': ['water'], 
'quaquaval': ['water', 'fighting'], 
'lechonk': ['normal'], 
'oinkologne': ['normal'], 
'tarountula': ['bug'], 
'spidops': ['bug'], 
'nymble': ['bug'], 
'lokix': ['bug', 'dark'], 
'hoppip': ['grass', 'flying'], 
'skiploom': ['grass', 'flying'], 
'jumpluff': ['grass', 'flying'], 
'fletchling': ['normal', 'flying'], 
'fletchinder': ['fire', 'flying'], 
'talonflame': ['fire', 'flying'], 
'pawmi': ['electric'], 
'pawmo': ['electric', 'fighting'], 
'pawmot': ['electric', 'fighting'], 
'houndour': ['dark', 'fire'], 
'houndoom': ['dark', 'fire'], 
'yungoos': ['normal'], 
'gumshoos': ['normal'], 
'skwovet': ['normal'], 
'greedent': ['normal'], 
'sunkern': ['grass'], 
'sunflora': ['grass'], 
'kricketot': ['bug'], 
'kricketune': ['bug'], 
'scatterbug': ['bug'], 
'spewpa': ['bug'], 
'vivillon': ['bug', 'flying'], 
'combee': ['bug', 'flying'], 
'vespiquen': ['bug', 'flying'], 
'rookidee': ['flying'], 
'corvisquire': ['flying'], 
'corviknight': ['flying', 'steel'], 
'happiny': ['normal'], 
'chansey': ['normal'], 
'blissey': ['normal'], 
'azurill': ['normal', 'fairy'], 
'marill': ['water', 'fairy'], 
'azumarill': ['water', 'fairy'], 
'surskit': ['bug', 'water'], 
'masquerain': ['bug', 'flying'], 
'buizel': ['water'], 
'floatzel': ['water'], 
'wooper': ['poison', 'ground'], 
'clodsire': ['poison', 'ground'], 
'psyduck': ['water'], 
'golduck': ['water'], 
'chewtle': ['water'], 
'drednaw': ['water', 'rock'], 
'igglybuff': ['normal', 'fairy'], 
'jigglypuff': ['normal', 'fairy'], 
'wigglytuff': ['normal', 'fairy'], 
'ralts': ['psychic', 'fairy'], 
'kirlia': ['psychic', 'fairy'], 
'gardevoir': ['psychic', 'fairy'], 
'gallade': ['psychic', 'fighting'], 
'drowzee': ['psychic'], 
'hypno': ['psychic'], 
'gastly': ['ghost', 'poison'], 
'haunter': ['ghost', 'poison'], 
'gengar': ['ghost', 'poison'], 
'tandemaus': ['normal'], 
'maushold': ['normal'], 
'pichu': ['electric'], 
'pikachu': ['electric'], 
'raichu': ['electric'], 
'fidough': ['fairy'], 
'dachsbun': ['fairy'], 
'slakoth': ['normal'], 
'vigoroth': ['normal'], 
'slaking': ['normal'], 
'bounsweet': ['grass'], 
'steenee': ['grass'], 
'tsareena': ['grass'], 
'smoliv': ['grass', 'normal'], 
'dolliv': ['grass', 'normal'], 
'arboliva': ['grass', 'normal'], 
'bonsly': ['rock'], 
'sudowoodo': ['rock'], 
'rockruff': ['rock'], 
'lycanroc': ['rock'], 
'rolycoly': ['rock'], 
'carkol': ['rock', 'fire'], 
'coalossal': ['rock', 'fire'], 
'shinx': ['electric'], 
'luxio': ['electric'], 
'luxray': ['electric'], 
'starly': ['normal', 'flying'], 
'staravia': ['normal', 'flying'], 
'staraptor': ['normal', 'flying'], 
'oricorio': ['fire', 'flying'], 
'mareep': ['electric'], 
'flaaffy': ['electric'], 
'ampharos': ['electric'], 
'petilil': ['grass'], 
'lilligant': ['grass'], 
'shroomish': ['grass'], 
'breloom': ['grass', 'fighting'], 
'applin': ['grass', 'dragon'], 
'flapple': ['grass', 'dragon'], 
'appletun': ['grass', 'dragon'], 
'spoink': ['psychic'], 
'grumpig': ['psychic'], 
'squawkabilly': ['normal', 'flying'], 
'misdreavus': ['ghost'], 
'mismagius': ['ghost'], 
'makuhita': ['fighting'], 
'hariyama': ['fighting'], 
'crabrawler': ['fighting'], 
'crabominable': ['fighting', 'ice'], 
'salandit': ['poison', 'fire'], 
'salazzle': ['poison', 'fire'], 
'phanpy': ['ground'], 
'donphan': ['ground'], 
'cufant': ['steel'], 
'copperajah': ['steel'], 
'gible': ['dragon', 'ground'], 
'gabite': ['dragon', 'ground'], 
'garchomp': ['dragon', 'ground'], 
'nacli': ['rock'], 
'naclstack': ['rock'], 
'garganacl': ['rock'], 
'wingull': ['water', 'flying'], 
'pelipper': ['water', 'flying'], 
'magikarp': ['water'], 
'gyarados': ['water', 'flying'], 
'arrokuda': ['water'], 
'barraskewda': ['water'], 
'basculin': ['water'], 
'gulpin': ['poison'], 
'swalot': ['poison'], 
'meowth': ['normal'], 
'persian': ['normal'], 
'drifloon': ['ghost', 'flying'], 
'drifblim': ['ghost', 'flying'], 
'flab�b�': ['fairy'], 
'floette': ['fairy'], 
'florges': ['fairy'], 
'diglett': ['ground'], 
'dugtrio': ['ground'], 
'torkoal': ['fire'], 
'numel': ['fire', 'ground'], 
'camerupt': ['fire', 'ground'], 
'bronzor': ['steel', 'psychic'], 
'bronzong': ['steel', 'psychic'], 
'axew': ['dragon'], 
'fraxure': ['dragon'], 
'haxorus': ['dragon'], 
'mankey': ['fighting'], 
'primeape': ['fighting'], 
'annihilape': ['fighting', 'ghost'], 
'meditite': ['fighting', 'psychic'], 
'medicham': ['fighting', 'psychic'], 
'riolu': ['fighting'], 
'lucario': ['fighting', 'steel'], 
'charcadet': ['fire'], 
'armarouge': ['fire', 'psychic'], 
'ceruledge': ['fire', 'ghost'], 
'barboach': ['water', 'ground'], 
'whiscash': ['water', 'ground'], 
'tadbulb': ['electric'], 
'bellibolt': ['electric'], 
'goomy': ['dragon'], 
'sliggoo': ['dragon'], 
'goodra': ['dragon'], 
'croagunk': ['poison', 'fighting'], 
'toxicroak': ['poison', 'fighting'], 
'wattrel': ['electric', 'flying'], 
'kilowattrel': ['electric', 'flying'], 
'eevee': ['normal'], 
'vaporeon': ['water'], 
'jolteon': ['electric'], 
'flareon': ['fire'], 
'espeon': ['psychic'], 
'umbreon': ['dark'], 
'leafeon': ['grass'], 
'glaceon': ['ice'], 
'sylveon': ['fairy'], 
'dunsparce': ['normal'], 
'dudunsparce': ['normal'], 
'deerling': ['normal', 'grass'], 
'sawsbuck': ['normal', 'grass'], 
'girafarig': ['normal', 'psychic'], 
'farigiraf': ['normal', 'psychic'], 
'grimer': ['poison'], 
'muk': ['poison'], 
'maschiff': ['dark'], 
'mabosstiff': ['dark'], 
'toxel': ['electric', 'poison'], 
'toxtricity': ['electric', 'poison'], 
'dedenne': ['electric', 'fairy'], 
'pachirisu': ['electric'], 
'shroodle': ['poison', 'normal'], 
'grafaiai': ['poison', 'normal'], 
'stantler': ['normal'], 
'foongus': ['grass', 'poison'], 
'amoonguss': ['grass', 'poison'], 
'voltorb': ['electric'], 
'electrode': ['electric'], 
'magnemite': ['electric', 'steel'], 
'magneton': ['electric', 'steel'], 
'magnezone': ['electric', 'steel'], 
'ditto': ['normal'], 
'growlithe': ['fire'], 
'arcanine': ['fire'], 
'teddiursa': ['normal'], 
'ursaring': ['normal'], 
'zangoose': ['normal'], 
'seviper': ['poison'], 
'swablu': ['normal', 'flying'], 
'altaria': ['dragon', 'flying'], 
'skiddo': ['grass'], 
'gogoat': ['grass'], 
'tauros': ['fighting'], 
'litleo': ['fire', 'normal'], 
'pyroar': ['fire', 'normal'], 
'stunky': ['poison', 'dark'], 
'skuntank': ['poison', 'dark'], 
'zorua': ['dark'], 
'zoroark': ['dark'], 
'sneasel': ['dark', 'ice'], 
'weavile': ['dark', 'ice'], 
'murkrow': ['dark', 'flying'], 
'honchkrow': ['dark', 'flying'], 
'gothita': ['psychic'], 
'gothorita': ['psychic'], 
'gothitelle': ['psychic'], 
'sinistea': ['ghost'], 
'polteageist': ['ghost'], 
'mimikyu': ['ghost', 'fairy'], 
'klefki': ['steel', 'fairy'], 
'indeedee': ['psychic', 'normal'], 
'bramblin': ['grass', 'ghost'], 
'brambleghast': ['grass', 'ghost'], 
'toedscool': ['ground', 'grass'], 
'toedscruel': ['ground', 'grass'], 
'tropius': ['grass', 'flying'], 
'fomantis': ['grass'], 
'lurantis': ['grass'], 
'klawf': ['rock'], 
'capsakid': ['grass'], 
'scovillain': ['grass', 'fire'], 
'cacnea': ['grass'], 
'cacturne': ['grass', 'dark'], 
'rellor': ['bug'], 
'rabsca': ['bug', 'psychic'], 
'venonat': ['bug', 'poison'], 
'venomoth': ['bug', 'poison'], 
'pineco': ['bug'], 
'forretress': ['bug', 'steel'], 
'scyther': ['bug', 'flying'], 
'scizor': ['bug', 'steel'], 
'heracross': ['bug', 'fighting'], 
'flittle': ['psychic'], 
'espathra': ['psychic'], 
'hippopotas': ['ground'], 
'hippowdon': ['ground'], 
'sandile': ['ground', 'dark'], 
'krokorok': ['ground', 'dark'], 
'krookodile': ['ground', 'dark'], 
'silicobra': ['ground'], 
'sandaconda': ['ground'], 
'mudbray': ['ground'], 
'mudsdale': ['ground'], 
'larvesta': ['bug', 'fire'], 
'volcarona': ['bug', 'fire'], 
'bagon': ['dragon'], 
'shelgon': ['dragon'], 
'salamence': ['dragon', 'flying'], 
'tinkatink': ['fairy', 'steel'], 
'tinkatuff': ['fairy', 'steel'], 
'tinkaton': ['fairy', 'steel'], 
'hatenna': ['psychic'], 
'hattrem': ['psychic'], 
'hatterene': ['psychic', 'fairy'], 
'impidimp': ['dark', 'fairy'], 
'morgrem': ['dark', 'fairy'], 
'grimmsnarl': ['dark', 'fairy'], 
'wiglett': ['water'], 
'wugtrio': ['water'], 
'bombirdier': ['flying', 'dark'], 
'finizen': ['water'], 
'palafin': ['water'], 
'varoom': ['steel', 'poison'], 
'revavroom': ['steel', 'poison'], 
'cyclizar': ['dragon', 'normal'], 
'orthworm': ['steel'], 
'sableye': ['dark', 'ghost'], 
'shuppet': ['ghost'], 
'banette': ['ghost'], 
'falinks': ['fighting'], 
'hawlucha': ['fighting', 'flying'], 
'spiritomb': ['ghost', 'dark'], 
'noibat': ['flying', 'dragon'], 
'noivern': ['flying', 'dragon'], 
'dreepy': ['dragon', 'ghost'], 
'drakloak': ['dragon', 'ghost'], 
'dragapult': ['dragon', 'ghost'], 
'glimmet': ['rock', 'poison'], 
'glimmora': ['rock', 'poison'], 
'rotom': ['electric', 'ghost'], 
'greavard': ['ghost'], 
'houndstone': ['ghost'], 
'oranguru': ['normal', 'psychic'], 
'passimian': ['fighting'], 
'komala': ['normal'], 
'larvitar': ['rock', 'ground'], 
'pupitar': ['rock', 'ground'], 
'tyranitar': ['rock', 'dark'], 
'stonjourner': ['rock'], 
'eiscue': ['ice'], 
'pincurchin': ['electric'], 
'sandygast': ['ghost', 'ground'], 
'palossand': ['ghost', 'ground'], 
'slowpoke': ['water', 'psychic'], 
'slowbro': ['water', 'psychic'], 
'slowking': ['water', 'psychic'], 
'shellos': ['water'], 
'gastrodon': ['water', 'ground'], 
'shellder': ['water'], 
'cloyster': ['water', 'ice'], 
'qwilfish': ['water', 'poison'], 
'luvdisc': ['water'], 
'finneon': ['water'], 
'lumineon': ['water'], 
'bruxish': ['water', 'psychic'], 
'alomomola': ['water'], 
'skrelp': ['poison', 'water'], 
'dragalge': ['poison', 'dragon'], 
'clauncher': ['water'], 
'clawitzer': ['water'], 
'tynamo': ['electric'], 
'eelektrik': ['electric'], 
'eelektross': ['electric'], 
'mareanie': ['poison', 'water'], 
'toxapex': ['poison', 'water'], 
'flamigo': ['flying', 'fighting'], 
'dratini': ['dragon'], 
'dragonair': ['dragon'], 
'dragonite': ['dragon', 'flying'], 
'snom': ['ice', 'bug'], 
'frosmoth': ['ice', 'bug'], 
'snover': ['grass', 'ice'], 
'abomasnow': ['grass', 'ice'], 
'delibird': ['ice', 'flying'], 
'cubchoo': ['ice'], 
'beartic': ['ice'], 
'snorunt': ['ice'], 
'glalie': ['ice'], 
'froslass': ['ice', 'ghost'], 
'cryogonal': ['ice'], 
'cetoddle': ['ice'], 
'cetitan': ['ice'], 
'bergmite': ['ice'], 
'avalugg': ['ice'], 
'rufflet': ['normal', 'flying'], 
'braviary': ['normal', 'flying'], 
'pawniard': ['dark', 'steel'], 
'bisharp': ['dark', 'steel'], 
'kingambit': ['dark', 'steel'], 
'deino': ['dark', 'dragon'], 
'zweilous': ['dark', 'dragon'], 
'hydreigon': ['dark', 'dragon'], 
'veluza': ['water', 'psychic'], 
'dondozo': ['water'], 
'tatsugiri': ['dragon', 'water'], 
'great tusk': ['ground', 'fighting'], 
'scream tail': ['fairy', 'psychic'], 
'brute bonnet': ['grass', 'dark'], 
'flutter mane': ['ghost', 'fairy'], 
'slither wing': ['bug', 'fighting'], 
'sandy shocks': ['electric', 'ground'], 
'iron treads': ['ground', 'steel'], 
'iron bundle': ['ice', 'water'], 
'iron hands': ['fighting', 'electric'], 
'iron jugulis': ['dark', 'flying'], 
'iron moth': ['fire', 'poison'], 
'iron thorns': ['rock', 'electric'], 
'frigibax': ['dragon', 'ice'], 
'arctibax': ['dragon', 'ice'], 
'baxcalibur': ['dragon', 'ice'], 
'gimmighoul': ['ghost'], 
'gholdengo': ['steel', 'ghost'], 
'wo-chien': ['dark', 'grass'], 
'chien-pao': ['dark', 'ice'], 
'ting-lu': ['dark', 'ground'], 
'chi-yu': ['dark', 'fire'], 
'roaring moon': ['dragon', 'dark'], 
'iron valiant': ['fairy', 'fighting'], 
'koraidon': ['fighting', 'dragon'], 
'miraidon': ['electric', 'dragon'], 
'sawsbuck autum': ['normal', 'grass'], 
'sawsbuck winter': ['normal', 'grass']
};
